### ISSUE TITLE
Add an "options" or "args" input to the task

### ISSUE THREAD

**Issue by AmaurySavarre** [aquasecurity/trivy-azure-pipelines-task#29]
Hello,
I added the task on a pipeline but it fails after 5 minutes on agents that have not run the task previously due to slow download time of the DB and unable to set the "--timeout" to prevent that.
Would it be possible to add an "options" or "args" to customise the command line executed ?

**Comment by ben-page** [comment]
Yep. Can't use this without the ability to specify the config.

**Comment by fsforza** [comment]
Hi, I opened a pull request to support any additional args to pass to the trivy cli. 
I don't know who and especially when will validate it
