### ISSUE TITLE
Unable to run trivy in docker mode when building with private Azure Agent in Kubernetes

### ISSUE THREAD

**Issue by Eneuman** [aquasecurity/trivy-azure-pipelines-task#3]
Hi

I'm trying to use trivy in a private Azure Agent running in Kubernetes and it gives me the following error:

```
2022-07-04T08:14:38.113Z	FATAL	image scan error: scan error: unable to initialize a scanner: unable to initialize a docker scanner: 4 errors occurred:
	* unable to inspect the image (***/myproject/myservice:4989): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
	* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory
	* containerd socket not found: /run/containerd/containerd.sock

```

This is probobly because Kubernetes does not support docker any more.

I'm running docker in a seperate container on my kubernetes cluster.
How can I tell trivy to use that docker instance?

In my Azure Build Agent, I'm doing this by changing the env variable like this:
- name: DOCKER_HOST
   value: tcp://localhost:2379

**Comment by liamg** [comment]
Hi @Eneuman - you can tell the task to download and run the trivy binary directly on the agent without using docker with:

```yaml
docker: false
```

**Comment by Eneuman** [comment]
@liamg Using the binaries directly worked :)
