### ISSUE TITLE
Feature request: Allow setting displayName to other than "trivy"

### ISSUE THREAD

**Issue by Eneuman** [aquasecurity/trivy-azure-pipelines-task#4]
Setting the "displayName" for the task to anything other than "trivy" results in this error:

![image](https://user-images.githubusercontent.com/12099277/177119519-852886d2-9619-48d5-a7fc-1647ea01749d.png)

**Comment by liamg** [comment]
Good catch, looking at this now :eyes:

**Comment by liamg** [comment]
v1.3.1 is now building, should start working in ~10 minutes
