### ISSUE TITLE
Bug: Invalid link for misconfigurations in the result panel

### ISSUE THREAD

**Issue by Eneuman** [aquasecurity/trivy-azure-pipelines-task#5]
The links in the result panel does not work.
It takes you to a 404 not found page.

![image](https://user-images.githubusercontent.com/12099277/177263240-5111d338-df44-4de4-84bf-6933be26966e.png)

**Comment by liamg** [comment]
This was an issue with the AVD site if I remember correctly - it should be fixed now.
