### ISSUE TITLE
AzDO extension publish failure

### ISSUE THREAD

**Issue by yauhenyaulampyeu** [aquasecurity/trivy-azure-pipelines-task#68]
Hi, there is a publishing workflow failure
```
error: Received response 401 (Not Authorized). Check that your personal access token is correct and hasn't expired.
Error: Process completed with exit code 255.
```

![image](https://github.com/aquasecurity/trivy-azure-pipelines-task/assets/15855399/2f439ae3-94d3-4923-a1c1-135fcc300e35)

The latest version available on the marketplace is `1.4.1` and versions `1.4.2` and `1.5.0` are not published.

It looks like the PUBLISHER_TOKEN is expired. Can this be updated, please?

**Comment by roberthstrand** [comment]
Ping @simar7

**Comment by srinivasKandukuri** [comment]
@yauhenyaulampyeu  updated the PUBLISHER_TOKEN and re triggered failed job 
![image](https://github.com/user-attachments/assets/2cfa6547-0da0-4e14-9678-4632bb7f2419)

cc : @tonaim
