### ISSUE TITLE
Multiple Extensions on Azure Marketplace with different versions

### ISSUE THREAD

**Issue by zinklandi** [aquasecurity/trivy-azure-pipelines-task#71]
There are two extensions on the azure marketplace.

- [1] https://marketplace.visualstudio.com/items?itemName=AquaSecurityOfficial.trivy-official
- [2] https://marketplace.visualstudio.com/items?itemName=aquasec.aquasec

This repository links to the first extension [1]. The official webpage https://www.aquasec.com/integrations/ links to the second extensions [2]. The second [2] extension is not that up to date like the first one (regarding the releases).

What extension is now the real one / the one I can use?

**Comment by srinivasKandukuri** [comment]
@zinklandi  
[1] extension is trivy OSS
[2] extension is premium, if you want to connect with Aqua CSP, using token you can connect and use.
