### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by ikattur-ota** [aquasecurity/trivy-azure-pipelines-task#85]
Marketplace documentation [says](https://github.com/aquasecurity/trivy-azure-pipelines-task/blob/main/marketplace.md#configuration) that the task downloads `latest` trivy version by default, but this is incorrect.
Version number seems to be hard-coded: https://github.com/aquasecurity/trivy-azure-pipelines-task/blob/main/trivy-task/index.ts#L7

Right now the latest version is [v0.56.2](https://github.com/aquasecurity/trivy/releases) which isn't updated here.

**Comment by a-poluyanov** [comment]
Yes, that’s right, I had to register the version myself in order to download the latest one. It's a bug that it won't load the latest one, and this needs to be fixed.

**Comment by ikattur-ota** [comment]
I see that #45 is fixed, but there still seems to be an issue pulling the latest trivy release again. The task now says that `Latest Trivy version is v0.60.0` but proceeds to download v0.59.1 instead:

```
Starting: Trivy Scan
==============================================================================
Task         : Trivy
Description  : Trivy is the world’s most popular open source vulnerability and misconfiguration scanner. It is reliable, fast, extremely easy to use, and it works wherever you need it.
Version      : 1.8.6
Author       : Aqua Security
Help         : https://github.com/aquasecurity/trivy-azure-pipelines-task
==============================================================================
Run requested using local Trivy binary...
Finding correct Trivy version to install...
Fetching latest Trivy version from GitHub...
Latest Trivy version is v0.60.0
Downloading Trivy...
Downloading: https://github.com/aquasecurity/trivy/releases/download/v0.59.1/trivy_0.59.1_Linux-64bit.tar.gz
Extracting Trivy...
Extracting archive

```
cc @owenrumney

**Comment by owenrumney** [comment]
Hey @ikattur-ota  - you're right, looks like I was grabbing the latest version then not returning it so it was using the fallback version.

This is fixed and a new version will be available shortly
